var default_feeds = [
    "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    "https://www.washingtonpost.com/arcio/rss/category/politics/?itid=lk_inline_manual_2",
    "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    "https://feeds.npr.org/1001/rss.xml", //news
    "https://www.youtube.com/feeds/videos.xml?channel_id=UC6ZFN9Tx6xh-skXCuRHCDpQ", //PBS News Hour
    "https://theconversation.com/us/articles.atom",
    "http://www.newyorker.com/feed/everything",
    "https://feeds.arstechnica.com/arstechnica/index",
    "https://feeds.feedburner.com/brainpickings/rss",
    "https://botsin.space/@APoD.rss"
]        

var papers_feeds = [
    "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Space.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/charles-m-blow/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/jamelle-bouie/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/david-brooks/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/frank-bruni/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/gail-collins/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/ross-douthat/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/maureen-dowd/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/thomas-l-friedman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/michelle-goldberg/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/ezra-klein/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/nicholas-kristof/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/paul-krugman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/farhad-manjoo/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/bret-stephens/rss.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/sunday-review.xml",
    "https://www.washingtonpost.com/arcio/rss/category/politics/?itid=lk_inline_manual_2",
    "https://www.washingtonpost.com/arcio/rss/category/opinions/?itid=lk_inline_manual_7",
    "http://feeds.washingtonpost.com/rss/sports?itid=lk_inline_manual_20",
    "http://feeds.washingtonpost.com/rss/business/technology?itid=lk_inline_manual_31",
    "http://feeds.washingtonpost.com/rss/national?itid=lk_inline_manual_32",
    "http://feeds.washingtonpost.com/rss/world?itid=lk_inline_manual_36",
    "http://feeds.washingtonpost.com/rss/business?itid=lk_inline_manual_37",
    "http://feeds.washingtonpost.com/rss/lifestyle?itid=lk_inline_manual_38",
    "http://feeds.washingtonpost.com/rss/entertainment?itid=lk_inline_manual_39",
    "https://feeds.a.dj.com/rss/RSSOpinion.xml",
    "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    "https://feeds.a.dj.com/rss/RSSWSJD.xml",
    "https://feeds.a.dj.com/rss/RSSLifestyle.xml",
    "https://www.latimes.com/business/rss2.0.xml",
    "https://www.latimes.com/environment/rss2.0.xml",
    "https://www.latimes.com/entertainment-arts/rss2.0.xml",
    "https://www.latimes.com/food/rss2.0.xml",
    "https://www.latimes.com/lifestyle/rss2.0.xml",
    "https://www.latimes.com/obituaries/rss2.0.xml",
    "https://www.latimes.com/opinion/rss2.0.xml",
    "https://www.latimes.com/politics/rss2.0.xml",
    "https://www.latimes.com/science/rss2.0.xml",
    "https://www.latimes.com/sports/rss2.0.xml",
    "https://www.latimes.com/travel/rss2.0.xml",
    "https://www.latimes.com/world-nation/rss2.0.xml",
    // The Guardian
    "https://www.theguardian.com/us-news/rss",
    "https://www.theguardian.com/world/rss",
    "https://www.theguardian.com/us/environment/rss",
    "https://www.theguardian.com/us/soccer/rss",
    "https://www.theguardian.com/us/business/rss",
    "https://www.theguardian.com/us/technology/rss",
    "https://www.theguardian.com/science/rss",
    "https://www.theguardian.com/us-news/series/the-fight-for-democracy/rss"
]

var condenast_feeds = [
    "http://www.newyorker.com/feed/news",
    "http://www.newyorker.com/feed/culture",
    "http://www.newyorker.com/feed/humor",
    "http://www.newyorker.com/feed/tag/books/rss",
    "http://www.newyorker.com/feed/tech",
    "http://www.newyorker.com/feed/news/sporting-scene",   
    "https://www.vanityfair.com/feed/rss",
    "https://feeds.arstechnica.com/arstechnica/technology-lab",
    "https://feeds.arstechnica.com/arstechnica/tech-policy",
    "https://feeds.arstechnica.com/arstechnica/science",
    "https://feeds.arstechnica.com/arstechnica/features",
    "https://www.wired.com/feed/category/gear/latest/rss",
    "https://www.wired.com/feed/category/ideas/latest/rss",
    "https://www.wired.com/feed/category/science/latest/rss",
    "https://www.wired.com/feed/category/security/latest/rss",
    "https://www.wired.com/feed/category/backchannel/latest/rss",
    "https://www.wired.com/feed/tag/wired-guide/latest/rss",
    "https://www.wired.com/feed/tag/ai/latest/rss",
]

var magazine_feeds = [
    "http://www.newyorker.com/feed/news",
    "http://www.newyorker.com/feed/culture",
    "http://www.newyorker.com/feed/humor",
    "http://www.newyorker.com/feed/tag/books/rss",
    "http://www.newyorker.com/feed/tech",
    "http://www.newyorker.com/feed/news/sporting-scene",   
    "https://www.vanityfair.com/feed/rss",
    "https://www.economist.com/the-world-this-week/rss.xml",
    "https://www.economist.com/letters/rss.xml",
    "https://www.economist.com/leaders/rss.xml",
    "https://www.economist.com/briefing/rss.xml",
    "https://www.economist.com/special-report/rss.xml",
    "https://www.economist.com/britain/rss.xml",
    "https://www.economist.com/europe/rss.xml",
    "https://www.economist.com/united-states/rss.xml",
    "https://www.economist.com/the-americas/rss.xml",
    "https://www.economist.com/middle-east-and-africa/rss.xml",
    "https://www.economist.com/asia/rss.xml",
    "https://www.economist.com/china/rss.xml",
    "https://www.economist.com/international/rss.xml",
    "https://www.economist.com/business/rss.xml",
    "https://www.economist.com/finance-and-economics/rss.xml",
    "https://www.economist.com/books-and-arts/rss.xml",
    "https://www.economist.com/obituary/rss.xml",
    "https://www.economist.com/graphic-detail/rss.xml",
    "https://www.economist.com/economic-and-financial-indicators/rss.xml",
    "https://www.economist.com/science-and-technology/rss.xml",
    "https://www.theatlantic.com/feed/all/",
    "https://www.wired.com/feed/category/business/latest/rss",
    "https://www.wired.com/feed/tag/ai/latest/rss",
    "https://www.wired.com/feed/category/culture/latest/rss",
    "https://www.wired.com/feed/category/gear/latest/rss",
    "https://www.wired.com/feed/category/ideas/latest/rss",
    "https://www.wired.com/feed/category/science/latest/rss",
    "https://www.wired.com/feed/category/security/latest/rss",
    "https://www.wired.com/feed/category/backchannel/latest/rss",
    "https://www.wired.com/feed/tag/wired-guide/latest/rss",
    "https://www.rollingstone.com/music/feed/",
    "https://www.rollingstone.com/politics/feed/",
    "https://www.rollingstone.com/tv-movies/feed/",
    "https://www.rollingstone.com/culture/feed/",
    "https://www.rollingstone.com/product-recommendations/feed/",
    "https://api.quantamagazine.org/feed/",
    "https://nautil.us/feed/",
    "https://aeon.co/philosophy.rss",
    "https://aeon.co/science.rss",
    "https://aeon.co/psychology.rss",
    "https://aeon.co/society.rss",
    "https://aeon.co/culture.rss"
]

var scifi_shorts_feed = [
    "https://clarkesworldmagazine.com/feed/",
    "https://www.lightspeedmagazine.com/rss-2/",
    "https://escapepod.org/feed/podcast/"
]

var geeek_feeds = [
    "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Space.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    "http://feeds.washingtonpost.com/rss/business/technology?itid=lk_inline_manual_31",
    "https://www.latimes.com/science/rss2.0.xml",
    "https://feeds.npr.org/1007/rss.xml", //science
    "https://feeds.a.dj.com/rss/RSSWSJD.xml", // Tech
    "http://www.newyorker.com/feed/tech",
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "https://www.theguardian.com/us/technology/rss",
    "https://www.theguardian.com/science/rss",
    "https://www.economist.com/science-and-technology/rss.xml",
    "https://feeds.bloomberg.com/technology/news.rss",
    "https://feeds.arstechnica.com/arstechnica/technology-lab",
    "https://feeds.arstechnica.com/arstechnica/tech-policy",
    "https://feeds.arstechnica.com/arstechnica/science",
    "https://feeds.arstechnica.com/arstechnica/features",
    "https://www.technologyreview.com/feed/",
    "https://www.wired.com/feed/category/business/latest/rss",
    "https://www.wired.com/feed/tag/ai/latest/rss",
    "https://www.wired.com/feed/category/culture/latest/rss",
    "https://www.wired.com/feed/category/gear/latest/rss",
    "https://www.wired.com/feed/category/ideas/latest/rss",
    "https://www.wired.com/feed/category/science/latest/rss",
    "https://www.wired.com/feed/category/security/latest/rss",
    "https://www.wired.com/feed/category/backchannel/latest/rss",
    "https://www.wired.com/feed/tag/wired-guide/latest/rss",
    "https://theconversation.com/us/technology/articles.atom",
    "https://phys.org/rss-feed/earth-news/",
    "https://phys.org/rss-feed/science-news/",
    "https://phys.org/rss-feed/nanotech-news/",
    "https://phys.org/rss-feed/physics-news/",
    "https://phys.org/rss-feed/space-news/",
    "https://phys.org/rss-feed/biology-news/",
    "https://phys.org/rss-feed/chemistry-news/",
    "https://thegradient.pub/rss/",
    "https://www.ailawlibrarians.com/feed/",
    "https://slate.com/feeds/technology.rss",
    "http://gizmodo.com/vip.xml",
    "https://techcrunch.com/feed/",
    "https://www.techdirt.com/techdirt_rss.xml",
    "https://www.theinformation.com/feed",
    "https://pluralistic.net/feed/",
    "https://xkcd.com/rss.xml",
    "https://feeds.feedburner.com/mcsweeneys",
    "https://spacenews.com/feed/",
    "https://hnrss.org/best",
    "https://screenrant.com/feed/tag/star-trek/",
    "https://api.quantamagazine.org/feed/",
    "https://nautil.us/feed/",
    "https://aeon.co/philosophy.rss",
    "https://aeon.co/science.rss",
    "https://aeon.co/psychology.rss",
    "https://badastronomy.substack.com/feed/",
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw", //3blue1brown
    "https://www.youtube.com/feeds/videos.xml?channel_id=UC415bOPUcGSamy543abLmRA", //Cleo Abram
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA", //Veritasium 
    "https://botsin.space/@APoD.rss",
    "https://tor.com/feed"
]

geeek_feeds = geeek_feeds.concat(scifi_shorts_feed)

// .edu domains linked to from https://www.americanbar.org/groups/legal_education/resources/aba_approved_law_schools/in_alphabetical_order/
var law_schools = [
    "uakron.edu",
    "law.ua.edu",
    "albanylaw.edu",
    "wcl.american.edu",
    "asl.edu",
    "law.arizona.edu",
    "asu.edu",
    "uark.edu",
    "johnmarshall.edu",
    "avemarialaw.edu",
    "ubalt.edu",
    "barry.edu",
    "baylor.edu",
    "belmont.edu",
    "bc.edu",
    "bu.edu",
    "law.byu.edu",
    "brooklaw.edu",
    "law.buffalo.edu",
    "law.berkeley.edu",
    "law.ucdavis.edu",
    "uchastings.edu",
    "law.uci.edu",
    "law.ucla.edu",
    "cwsl.edu",
    "campbell.edu",
    "law.capital.edu",
    "case.edu",
    "chapman.edu",
    "charlestonlaw.edu",
    "law.uchicago.edu",
    "kentlaw.edu",
    "law.uc.edu",
    "law.cuny.edu",
    "law.csuohio.edu",
    "colorado.edu",
    "law.columbia.edu",
    "law.uconn.edu",
    "lawschool.cornell.edu",
    "creighton.edu",
    "udayton.edu",
    "law.du.edu",
    "depaul.edu",
    "udmercy.edu",
    "udc.edu",
    "law.drake.edu",
    "drexel.edu",
    "law.duke.edu",
    "duq.edu",
    "elon.edu",
    "law.emory.edu",
    "faulkner.edu",
    "law.ufl.edu",
    "fcsl.edu",
    "famu.edu",
    "fcsl.edu",
    "fiu.edu",
    "law.fsu.edu",
    "fordham.edu",
    "law.gmu.edu",
    "law.georgetown.edu",
    "law.gwu.edu",
    "law.uga.edu",
    "georgetown.edu",
    "gsu.edu",
    "ggu.edu",
    "law.gonzaga.edu",
    "law.harvard.edu",
    "law.hawaii.edu",
    "hofstra.edu",
    "law.uh.edu",
    "howard.edu",
    "uidaho.edu",
    "uic.edu",
    "illinois.edu",
    "indiana.edu",
    "iu.edu",
    "derecho.inter.edu",
    "uiowa.edu",
    "uidaho.edu",
    "law.ku.edu",
    "uky.edu",
    "liberty.edu",
    "lmunet.edu",
    "lclark.edu",
    "law.lsu.edu",
    "law.louisville.edu",
    "luc.edu",
    "lls.edu",
    "loyno.edu",
    "maine.edu",
    "marquette.edu",
    "law.umaryland.edu",
    "umassd.edu",
    "mcgeorge.edu",
    "memphis.edu",
    "mercer.edu",
    "law.miami.edu",
    "law.msu.edu",
    "law.umich.edu",
    "law.umn.edu",
    "mc.edu",
    "law.olemiss.edu",
    "law.missouri.edu",
    "umkc.edu",
    "umt.edu",
    "unl.edu",
    "unlv.edu",
    "nesl.edu",
    "unm.edu",
    "unh.edu",
    "nyls.edu",
    "law.nyu.edu",
    "unc.edu",
    "nccu.edu",
    "law.und.edu",
    "northeastern.edu",
    "niu.edu",
    "nku.edu",
    "law.northwestern.edu",
    "nd.edu",
    "law.nova.edu",
    "onu.edu",
    "osu.edu",
    "law.ou.edu",
    "okcu.edu",
    "uoregon.edu",
    "law.pace.edu",
    "law.upenn.edu",
    "psu.edu",
    "pennstatelaw.psu.edu",
    "pepperdine.edu",
    "law.pitt.edu",
    "pucpr.edu",
    "uprrp.edu",
    "quinnipiac.edu",
    "regent.edu",
    "richmond.edu",
    "rwu.edu",
    "law.rutgers.edu",
    "stjohns.edu",
    "slu.edu",
    "stmarytx.edu",
    "stu.edu",
    "stthomas.edu",
    "samford.edu",
    "sandiego.edu",
    "usfca.edu",
    "scu.edu",
    "law.seattleu.edu",
    "shu.edu",
    "law.sc.edu",
    "usd.edu",
    "stcl.edu",
    "sulc.edu",
    "usc.edu",
    "siu.edu",
    "law.smu.edu",
    "stcl.edu",
    "swlaw.edu",
    "law.stanford.edu",
    "stetson.edu",
    "suffolk.edu",
    "law.syr.edu",
    "law.temple.edu",
    "law.utk.edu",
    "utexas.edu",
    "tamu.edu",
    "tsulaw.edu",
    "law.ttu.edu",
    "cooley.edu",
    "utoledo.edu",
    "tourolaw.edu",
    "law.tulane.edu",
    "utulsa.edu",
    "untdallas.edu",
    "law.utah.edu",
    "vanderbilt.edu",
    "vermontlaw.edu",
    "law.villanova.edu",
    "law.virginia.edu",
    "law.wfu.edu",
    "wlu.edu",
    "law.washington.edu",
    "wustl.edu",
    "law.wayne.edu",
    "wne.edu",
    "wsulaw.edu",
    "law.wvu.edu",
    "widener.edu",
    "widener.edu",
    "wm.edu",
    "law.wisc.edu",
    "uwyo.edu",
    "law.yale.edu",
    "cardozo.yu.edu"
    ]

//  domains found at https://network.bepress.com/institutions/law/ with /recent.rss appended to the end
var dc_law_feeds = [
    "https://digitalcommons.acu.edu/recent.rss",
    "https://arc.accesslex.org/recent.rss",
    "https://institutionalrepository.aah.org/recent.rss",
    "https://ecommons.aku.edu/recent.rss",
    "https://scholar.afit.edu/recent.rss",
    "https://digitalcommons.wcl.american.edu/recent.rss",
    "https://fount.aucegypt.edu/recent.rss",
    "https://digitalcommons.andrews.edu/recent.rss",
    "https://aura.antioch.edu/recent.rss",
    "https://scholarworks.arcadia.edu/recent.rss",
    "https://place.asburyseminary.edu/recent.rss",
    "https://jle.aals.org/recent.rss",
    "https://digitalcommons.aaru.edu.jo/recent.rss",
    "https://digitalcommons.assumption.edu/recent.rss",
    "https://archium.ateneo.edu/recent.rss",
    "https://idun.augsburg.edu/recent.rss",
    "https://digitalcommons.augustana.edu/recent.rss",
    "https://www.journal.acorn.org.au/recent.rss",
    "https://research.acer.edu.au/recent.rss",
    "https://research.avondale.edu.au/recent.rss",
    "https://law.bepress.com/recent.rss",
    "https://digitalcommons.bard.edu/recent.rss",
    "https://lawpublications.barry.edu/recent.rss",
    "https://digitalcommons.bau.edu.lb/recent.rss",
    "https://scholarworks.bellarmine.edu/recent.rss",
    "https://repository.belmont.edu/recent.rss",
    "https://scholars.bentley.edu/recent.rss",
    "https://orb.binghamton.edu/recent.rss",
    "https://scholarworks.boisestate.edu/recent.rss",
    "https://scholarship.law.bu.edu/recent.rss",
    "https://digitalcommons.bowdoin.edu/recent.rss",
    "https://scholarworks.bgsu.edu/recent.rss",
    "https://digitalcommons.bridgewater.edu/recent.rss",
    "https://vc.bridgew.edu/recent.rss",
    "https://scholarsarchive.byu.edu/recent.rss",
    "https://digitalcommons.law.byu.edu/recent.rss",
    "https://brooklynworks.brooklaw.edu/recent.rss",
    "https://digitalcommons.bryant.edu/recent.rss",
    "https://digitalcommons.bucknell.edu/recent.rss",
    "https://digitalcommons.butler.edu/recent.rss",
    "https://digitalcommons.humboldt.edu/recent.rss",
    "https://digitalcommons.calpoly.edu/recent.rss",
    "https://digitalcommons.csumb.edu/recent.rss",
    "https://scholarworks.lib.csusb.edu/recent.rss",
    "https://scholarlycommons.law.cwsl.edu/recent.rss",
    "https://digitalcommons.calvin.edu/recent.rss",
    "https://scholarship.law.campbell.edu/recent.rss",
    "https://scholarlycommons.law.case.edu/recent.rss",
    "https://digitalcommons.cedarville.edu/recent.rss",
    "https://cbe.miis.edu/recent.rss",
    "https://digitalcommons.centracare.com/recent.rss",
    "https://dc.cbn.gov.ng/recent.rss",
    "https://digitalcommons.cwu.edu/recent.rss",
    "https://digitalcommons.chapman.edu/recent.rss",
    //"https://chapmanlaw.works.bepress.com/recent.rss", //unreadable feed
    "https://charlestonlaw.works.bepress.com/recent.rss",
    "https://scholarship.kentlaw.iit.edu/recent.rss",
    "https://bulletinofcas.researchcommons.org/recent.rss",
    "https://digital.car.chula.ac.th/recent.rss",
    "https://academicworks.cuny.edu/recent.rss",
    "https://scholarship.claremont.edu/recent.rss",
    "https://commons.clarku.edu/recent.rss",
    "https://tigerprints.clemson.edu/recent.rss",
    "https://engagedscholarship.csuohio.edu/recent.rss",
    "https://digitalcommons.coastal.edu/recent.rss",
    "https://digitalcommons.colby.edu/recent.rss",
    "https://digitalcommons.csbsju.edu/recent.rss",
    "https://crossworks.holycross.edu/recent.rss",
    "https://digitalcommons.collin.edu/recent.rss",
    "https://digitalcommons.colum.edu/recent.rss",
    "https://scholarship.law.columbia.edu/recent.rss",
    "https://digitalcommons.csp.edu/recent.rss",
    "https://digitalcommons.conncoll.edu/recent.rss",
    "https://scholarship.law.cornell.edu/recent.rss",
    "https://digitalcommons.daemen.edu/recent.rss",
    "https://scholar.dsu.edu/recent.rss",
    "https://digitalcommons.dartmouth.edu/recent.rss",
    "https://animorepository.dlsu.edu.ph/recent.rss",
    "https://via.library.depaul.edu/recent.rss",
    "https://scholarship.depauw.edu/recent.rss",
    "https://library.dpird.wa.gov.au/recent.rss",
    "https://scholar.dominican.edu/recent.rss",
    "https://digitalcollections.dordt.edu/recent.rss",
    //"http://drexellaw.works.bepress.com/recent.rss", //unreadable feed
    "https://scholarship.law.duke.edu/recent.rss",
    "https://dsc.duq.edu/recent.rss",
    //"https://duquesnelaw.works.bepress.com/recent.rss", //unreadable feed
    "https://dc.etsu.edu/recent.rss",
    "https://thekeep.eiu.edu/recent.rss",
    "https://encompass.eku.edu/recent.rss",
    "https://commons.emich.edu/recent.rss",
    "https://dc.ewu.edu/recent.rss",
    "https://ro.ecu.edu.au/recent.rss",
    "https://commons.erau.edu/recent.rss",
    "https://scholarlycommons.law.emory.edu/recent.rss",
    "https://digitalcommons.uncfsu.edu/recent.rss",
    "https://commons.law.famu.edu/recent.rss",
    "https://digitalcommons.fiu.edu/recent.rss",
    "https://ecollections.law.fiu.edu/recent.rss",
    "https://ir.law.fsu.edu/recent.rss",
    "https://griffinshare.fontbonne.edu/recent.rss",
    "https://ir.lawnet.fordham.edu/recent.rss",
    "https://research.library.fordham.edu/recent.rss",
    "https://scholars.fhsu.edu/recent.rss",
    "https://fuse.franklin.edu/recent.rss",
    "https://oer.galileo.usg.edu/recent.rss",
    "https://digitalcommons.gardner-webb.edu/recent.rss",
    "https://digitalcommons.georgefox.edu/recent.rss",
    "https://scholarship.law.gwu.edu/recent.rss",
    "https://scholarship.law.georgetown.edu/recent.rss",
    "https://digitalcommons.gaacademy.org/recent.rss",
    "https://kb.gcsu.edu/recent.rss",
    "https://digitalcommons.georgiasouthern.edu/recent.rss",
    "https://scholarworks.gsu.edu/recent.rss",
    "https://readingroom.law.gsu.edu/recent.rss",
    "https://cupola.gettysburg.edu/recent.rss",
    "https://digitalcommons.law.ggu.edu/recent.rss",
    "https://repository.gonzaga.edu/recent.rss",
    "https://opus.govst.edu/recent.rss",
    "https://scholarworks.gvsu.edu/recent.rss",
    "https://helindigitalcommons.org/recent.rss",
    "https://digitalcommons.hamilton.edu/recent.rss",
    "https://digitalcommons.hamline.edu/recent.rss",
    "https://scholarworks.harding.edu/recent.rss",
    "https://hsrc.himmelfarb.gwu.edu/recent.rss",
    "https://digitalcommons.hollins.edu/recent.rss",
    "https://dh.howard.edu/recent.rss",
    "https://digitalcommons.imsa.edu/recent.rss",
    "https://ir.library.illinoisstate.edu/recent.rss",
    "https://digitalcommons.iwu.edu/recent.rss",
    "https://ir.iba.edu.pk/recent.rss",
    "https://gensoken.toyo.ac.jp/recent.rss",
    "https://www.interscience.in/recent.rss",
    "https://digitalcommons.jsu.edu/recent.rss",
    "https://commons.lib.jmu.edu/recent.rss",
    "https://scholarsarchive.jwu.edu/recent.rss",
    "https://scholarspace.jccc.edu/recent.rss",
    "https://www.jpsa.ac.ae/recent.rss",
    "https://www.steps-journal.com/recent.rss",
    "https://newprairiepress.org/recent.rss",
    "https://digitalcommons.kean.edu/recent.rss",
    "https://digitalcommons.kennesaw.edu/recent.rss",
    "https://research.library.kutztown.edu/recent.rss",
    "https://digitalcommons.lasalle.edu/recent.rss",
    "https://dclu.langston.edu/recent.rss",
    "https://lux.lawrence.edu/recent.rss",
    "https://digitalcommons.lesley.edu/recent.rss",
    "https://lawcommons.lclark.edu/recent.rss",
    "https://digitalcommons.liberty.edu/recent.rss",
    "https://digitalcommons.lmunet.edu/recent.rss",
    "https://lincolnlaw.works.bepress.com/recent.rss",
    "https://bluetigercommons.lincolnu.edu/recent.rss",
    "https://digitalcommons.lindenwood.edu/recent.rss",
    "https://digitalcommons.linfield.edu/recent.rss",
    "https://commons.ln.edu.hk/recent.rss",
    "https://digitalcollections.lipscomb.edu/recent.rss",
    "https://scholarsrepository.llu.edu/recent.rss",
    "https://digitalcommons.liu.edu/recent.rss",
    "https://digitalcommons.longwood.edu/recent.rss",
    "https://digitalcommons.lsu.edu/recent.rss",
    "https://digitalcommons.law.lsu.edu/recent.rss",
    "https://digitalcommons.latech.edu/recent.rss",
    "https://digitalcommons.lmu.edu/recent.rss",
    "https://ecommons.luc.edu/recent.rss",
    "https://lawecommons.luc.edu/recent.rss",
    "https://digitalcommons.luthersem.edu/recent.rss",
    "https://spiral.lynn.edu/recent.rss",
    "https://digitalcommons.macalester.edu/recent.rss",
    "https://knowledgeconnection.mainehealth.org/recent.rss",
    "https://impressions.manipal.edu/recent.rss",
    "https://epublications.marquette.edu/recent.rss",
    "https://scholarship.law.marquette.edu/recent.rss",
    "https://mds.marshall.edu/recent.rss",
    "https://www.repository.law.indiana.edu/recent.rss",
    "https://scholarlycommons.law.hofstra.edu/recent.rss",
    "https://digitalcommons.law.mercer.edu/recent.rss",
    "https://scholarworks.merrimack.edu/recent.rss",
    "https://mosaic.messiah.edu/recent.rss",
    "https://digitalcommons.mtu.edu/recent.rss",
    //"https://uzjournals.edu.uz/recent.rss", //unreadable feed
    "https://cornerstone.lib.mnsu.edu/recent.rss",
    "https://digitalcommons.misericordia.edu/recent.rss",
    "https://dc.law.mc.edu/recent.rss",
    "https://scholarsjunction.msstate.edu/recent.rss",
    "https://athenacommons.muw.edu/recent.rss",
    "https://bearworks.missouristate.edu/recent.rss",
    "https://scholarsmine.mst.edu/recent.rss",
    "https://open.mitchellhamline.edu/recent.rss",
    "https://digitalcommons.molloy.edu/recent.rss",
    "https://digitalcommons.mtech.edu/recent.rss",
    "https://digitalcommons.montclair.edu/recent.rss",
    "https://scholarworks.moreheadstate.edu/recent.rss",
    "https://sword.cit.ie/recent.rss",
    "https://digitalcommons.murraystate.edu/recent.rss",
    "https://repository.nls.ac.in/recent.rss",
    "https://digitalcommons.nl.edu/recent.rss",
    "https://digitalcommons.njit.edu/recent.rss",
    "https://digitalcommons.nyls.edu/recent.rss",
    "https://digital.library.ncat.edu/recent.rss",
    "https://archives.law.nccu.edu/recent.rss",
    "https://neiudc.neiu.edu/recent.rss",
    "https://huskiecommons.lib.niu.edu/recent.rss",
    "https://commons.nmu.edu/recent.rss",
    "https://scholarlycommons.law.northwestern.edu/recent.rss",
    "https://scholarship.law.nd.edu/recent.rss",
    "https://nsuworks.nova.edu/recent.rss",
    "https://digitalcommons.onu.edu/recent.rss",
    "https://ohioopen.library.ohio.edu/recent.rss",
    "https://digitalcommons.owu.edu/recent.rss",
    "https://oculaw.works.bepress.com/recent.rss",
    "https://digitalcommons.odu.edu/recent.rss",
    "https://digitalcommons.olivet.edu/recent.rss",
    "https://digitalshowcase.oru.edu/recent.rss",
    "https://digitalcommons.osgoode.yorku.ca/recent.rss",
    "https://digitalcommons.otterbein.edu/recent.rss",
    "https://scholarlycommons.obu.edu/recent.rss",
    "https://digitalcommons.pace.edu/recent.rss",
    "https://spark.parkland.edu/recent.rss",
    "https://ideas.dickinsonlaw.psu.edu/recent.rss",
    "https://elibrary.law.psu.edu/recent.rss",
    "https://digitalcommons.pepperdine.edu/recent.rss",
    "https://digitalcommons.pittstate.edu/recent.rss",
    "https://knowledgecommons.popcouncil.org/recent.rss",
    "https://pdxscholar.library.pdx.edu/recent.rss",
    "https://digitalcommons.providence.edu/recent.rss",
    "https://docs.lib.purdue.edu/recent.rss",
    "https://epublications.regis.edu/recent.rss",
    "https://digitalcommons.ric.edu/recent.rss",
    "https://digitalcommons.risd.edu/recent.rss",
    "https://scholarworks.rit.edu/recent.rss",
    "https://docs.rwu.edu/recent.rss",
    "https://scholarship.rollins.edu/recent.rss",
    "https://ecommons.roseman.edu/recent.rss",
    "https://rdw.rowan.edu/recent.rss",
    "https://rutgerslawnewark.works.bepress.com/recent.rss",
    "https://www.ebrjournal.net/recent.rss",
    "https://digitalcollections.sit.edu/recent.rss",
    "https://dc.law.utah.edu/recent.rss",
    "https://knightscholar.geneseo.edu/recent.rss",
    "https://digitalcommons.sacredheart.edu/recent.rss",
    "https://scholarship.law.slu.edu/recent.rss",
    "https://digitalcommons.stmarys-ca.edu/recent.rss",
    "https://digitalcommons.salve.edu/recent.rss",
    "https://scholarworks.sjsu.edu/recent.rss",
    "https://digitalcommons.law.scu.edu/recent.rss",
    "https://scholarcommons.scu.edu/recent.rss",
    "https://digitalcommons.slc.edu/recent.rss",
    "https://digitalcommons.schulichlaw.dal.ca/recent.rss",
    "https://digitalcommons.spu.edu/recent.rss",
    "https://lawpublications.seattleu.edu/recent.rss",
    "https://scholarship.shu.edu/recent.rss",
    "https://source.sheridancollege.ca/recent.rss",
    "https://ink.library.smu.edu.sg/recent.rss",
    "https://creativematter.skidmore.edu/recent.rss",
    "https://digitalcommons.sia.edu/recent.rss",
    "https://openprairie.sdstate.edu/recent.rss",
    "https://firescholars.seu.edu/recent.rss",
    "https://knowledge.e.southern.edu/recent.rss",
    "https://opensiuc.lib.siu.edu/recent.rss",
    "https://spark.siue.edu/recent.rss",
    "https://scholar.smu.edu/recent.rss",
    "https://digitalcommons.subr.edu/recent.rss",
    "https://sophia.stkate.edu/recent.rss",
    "https://repository.stcloudstate.edu/recent.rss",
    "https://fisherpub.sjf.edu/recent.rss",
    "https://scholar.stjohns.edu/recent.rss",
    "https://scholarship.law.stjohns.edu/recent.rss",
    "https://commons.stmarytx.edu/recent.rss",
    "https://scholarship.stu.edu/recent.rss",
    "https://digitalcommons.buffalostate.edu/recent.rss",
    "https://scholarworks.sfasu.edu/recent.rss",
    "https://soar.stonehill.edu/recent.rss",
    "https://commons.library.stonybrook.edu/recent.rss",
    "https://dc.suffolk.edu/recent.rss",
    "https://works.swarthmore.edu/recent.rss",
    "https://surface.syr.edu/recent.rss",
    "https://arrow.tudublin.ie/recent.rss",
    "https://digitalscholarship.tnstate.edu/recent.rss",
    "https://scholarship.law.tamu.edu/recent.rss",
    "https://digitalcommons.tamuc.edu/recent.rss",
    "https://digitalcommons.tamusa.edu/recent.rss",
    "https://digitalscholarship.tsu.edu/recent.rss",
    "https://pxjournal.org/recent.rss",
    "https://buescholar.bue.edu.eg/recent.rss",
    "https://scholarship.law.edu/recent.rss",
    "https://openworks.wooster.edu/recent.rss",
    "https://mouseion.jax.org/recent.rss",
    "https://commons.allard.ubc.ca/recent.rss",
    "https://digitalcommons.library.tmc.edu/recent.rss",
    "https://ideaexchange.uakron.edu/recent.rss",
    "https://digitalcommons.library.umaine.edu/recent.rss",
    "https://researchonline.nd.edu.au/recent.rss",
    "https://repository.usfca.edu/recent.rss",
    "https://aquila.usm.edu/recent.rss",
    "https://falconcommons.utpb.edu/recent.rss",
    "https://jdc.jefferson.edu/recent.rss",
    "https://touroscholar.touro.edu/recent.rss",
    "https://digitalcommons.tourolaw.edu/recent.rss",
    "https://digitalrepository.trincoll.edu/recent.rss",
    "https://tuspubs.tuskegee.edu/recent.rss",
    "https://digital-commons.usnwc.edu/recent.rss",
    "https://repository.uclawsf.edu/recent.rss",
    "https://jnf.ufm.edu/recent.rss",
    "https://repository.law.uic.edu/recent.rss",
    "https://digitalcommons.law.uidaho.edu/recent.rss",
    "https://digitalcommons.umassglobal.edu/recent.rss",
    "https://press.armywarcollege.edu/recent.rss",
    "https://digitalworks.union.edu/recent.rss",
    "https://scholarworks.uaeu.ac.ae/recent.rss",
    //"https://digitalcommons.usmalibrary.org/recent.rss", //unreadable feed
    "https://ciencia.lasalle.edu.co/recent.rss",
    "https://scholarhub.ui.ac.id/recent.rss",
    "https://scholarsarchive.library.albany.edu/recent.rss",
    "https://digitalcommons.law.buffalo.edu/recent.rss",
    "https://knowledgecenter.ubt-uni.net/recent.rss",
    "https://scholarship.law.ua.edu/recent.rss",
    "https://louis.uah.edu/recent.rss",
    "https://lawrepository.ualr.edu/recent.rss",
    "https://scholarworks.uark.edu/recent.rss",
    "https://scholarworks.law.ubalt.edu/recent.rss",
    "https://scholarship.law.uci.edu/recent.rss",
    "https://stars.library.ucf.edu/recent.rss",
    "https://chicagounbound.uchicago.edu/recent.rss",
    "https://scholarship.law.uc.edu/recent.rss",
    "https://scholar.law.colorado.edu/recent.rss",
    "https://opencommons.uconn.edu/recent.rss",
    "https://ecommons.udayton.edu/recent.rss",
    "https://digitalcommons.du.edu/recent.rss",
    "https://scholarship.law.ufl.edu/recent.rss",
    "https://digitalcommons.law.uga.edu/recent.rss",
    "https://uknowledge.uky.edu/recent.rss",
    "https://repository.ulm.edu/recent.rss",
    "https://ir.library.louisville.edu/recent.rss",
    "https://digitalshowcase.lynchburg.edu/recent.rss",
    "https://digitalcommons.mainelaw.maine.edu/recent.rss",
    "https://scholar.umw.edu/recent.rss",
    "https://digitalcommons.law.umaryland.edu/recent.rss",
    "https://scholarworks.umass.edu/recent.rss",
    "https://scholarworks.umb.edu/recent.rss",
    "https://scholarship.law.umassd.edu/recent.rss",
    "https://digitalcommons.memphis.edu/recent.rss",
    //"https://scholarlyrepository.miami.edu/recent.rss", //unreadable feed
    "https://repository.law.miami.edu/recent.rss",
    "https://repository.law.umich.edu/recent.rss",
    "https://scholarship.law.umn.edu/recent.rss",
    "https://egrove.olemiss.edu/recent.rss",
    "https://scholarship.law.missouri.edu/recent.rss",
    "https://irl.umsl.edu/recent.rss",
    "https://irlaw.umkc.edu/recent.rss",
    "https://scholarworks.umt.edu/recent.rss",
    "https://digitalcommons.unl.edu/recent.rss",
    "https://digitalcommons.unmc.edu/recent.rss",
    "https://openspaces.unk.edu/recent.rss",
    "https://digitalcommons.unomaha.edu/recent.rss",
    "https://digitalscholarship.unlv.edu/recent.rss",
    "https://scholars.law.unlv.edu/recent.rss",
    "https://dune.une.edu/recent.rss",
    "https://scholars.unh.edu/recent.rss",
    "https://digitalcommons.newhaven.edu/recent.rss",
    "https://digitalrepository.unm.edu/recent.rss",
    "https://scholarworks.uno.edu/recent.rss",
    "https://scholarship.law.unc.edu/recent.rss",
    //"https://commons.und.edu/recent.rss",  //unreadable feed
    "https://digitalcommons.unf.edu/recent.rss",
    "https://digscholarship.unco.edu/recent.rss",
    "https://scholarworks.uni.edu/recent.rss",
    "https://digitalcommons.law.ou.edu/recent.rss",
    //"https://repository.upenn.edu/recent.rss", //unreadable feed
    "https://scholarship.law.upenn.edu/recent.rss",
    "https://scholarship.law.pitt.edu/recent.rss",
    //"https://pilotscholars.up.edu/recent.rss", //unreadable feed
    "https://soundideas.pugetsound.edu/recent.rss",
    "https://digitalcommons.uri.edu/recent.rss",
    "https://scholarship.richmond.edu/recent.rss",
    "https://digital.sandiego.edu/recent.rss",
    "https://scholarcommons.sc.edu/recent.rss",
    "https://red.library.usd.edu/recent.rss",
    "https://digitalcommons.usf.edu/recent.rss",
    "https://digitalcommons.usm.maine.edu/recent.rss",
    "https://soar.usa.edu/recent.rss",
    "https://ir.stthomas.edu/recent.rss",
    "https://ir.law.utk.edu/recent.rss",
    "https://scholar.utc.edu/recent.rss",
    "https://trace.tennessee.edu/recent.rss",
    "https://scholarworks.utrgv.edu/recent.rss",
    "https://scholarworks.utep.edu/recent.rss",
    "https://scholarworks.uttyler.edu/recent.rss",
    "https://digitalcommons.law.utulsa.edu/recent.rss",
    "https://scholarworks.uvm.edu/recent.rss",
    "https://digitalcommons.law.uw.edu/recent.rss",
    "https://digitalcommons.tacoma.uw.edu/recent.rss",
    "https://scholar.uwindsor.ca/recent.rss",
    "https://dc.uwm.edu/recent.rss",
    "https://ro.uow.edu.au/recent.rss",
    "https://scholarship.law.uwyo.edu/recent.rss",
    "https://digitalcommons.law.udc.edu/recent.rss",
    "https://athenaeum.uiw.edu/recent.rss",
    "https://scholarlycommons.pacific.edu/recent.rss",
    "https://www.ukdr.uplb.edu.ph/recent.rss",
    "https://digitalcommons.ursinus.edu/recent.rss",
    "https://digitalcommons.usu.edu/recent.rss",
    "https://scholar.valpo.edu/recent.rss",
    "https://scholarship.law.vanderbilt.edu/recent.rss",
    "https://digitalcommons.law.villanova.edu/recent.rss",
    "https://scholarscompass.vcu.edu/recent.rss",
    "https://commons.vccs.edu/recent.rss",
    "https://research.upjohn.org/recent.rss",
    "https://scholarworks.waldenu.edu/recent.rss",
    "https://openscholarship.wustl.edu/recent.rss",
    "https://scholarlycommons.law.wlu.edu/recent.rss",
    "https://digitalcommons.wayne.edu/recent.rss",
    "https://www.wellbeingintlstudiesrepository.org/recent.rss",
    "https://digitalcommons.wcupa.edu/recent.rss",
    "https://researchrepository.wvu.edu/recent.rss",
    "https://digitalcommons.wku.edu/recent.rss",
    "https://scholarworks.wmich.edu/recent.rss",
    "https://digitalcommons.law.wne.edu/recent.rss",
    //"https://ir.lib.uwo.ca/recent.rss", //unreadable feed
    "https://cedar.wwu.edu/recent.rss",
    "https://poetcommons.whittier.edu/recent.rss",
    "https://commonwealthlawwidener.works.bepress.com/recent.rss",
    "https://scholars.wlu.ca/recent.rss",
    "https://scholarworks.wm.edu/recent.rss",
    "https://scholarship.law.wm.edu/recent.rss",
    "https://openriver.winona.edu/recent.rss",
    "https://digitalcommons.winthrop.edu/recent.rss",
    "https://digitalcommons.wofford.edu/recent.rss",
    "https://commons.wmu.se/recent.rss",
    "https://corescholar.libraries.wright.edu/recent.rss",
    "https://digitalcommons.xula.edu/recent.rss",
    "https://elischolar.library.yale.edu/recent.rss",
    "https://larc.cardozo.yu.edu/recent.rss",
    "https://zuscholars.zu.ac.ae/recent.rss"
    ]

function filterListByStrings(A, B) {
    // Initialize an empty list C to store the filtered items
    let C = [];
    
    // Iterate through each item in list A
    for (let itemA of A) {
        // Flag to check if itemA contains any string from list B
        let containsStringFromB = false;
    
        // Iterate through each string in list B
        for (let stringB of B) {
        // Check if itemA contains the current string from B
        if (itemA.includes(stringB)) {
            containsStringFromB = true;
            break; // No need to check further once a match is found
        }
        }
    
        // If itemA contains any string from B, add it to list C
        if (containsStringFromB) {
        C.push(itemA);
        }
    }
    
    return C;
}
    
var law_school_feeds = filterListByStrings(dc_law_feeds, law_schools);

// These feeds are a mix of sites without paywalls and sites with paywalls for which 
// the Suffolk Law community has access. 
// See https://www.suffolk.edu/law/faculty-research/research/law-school-research-databases/washington-post
var suffolk_law_feeds = [
    "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Space.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/charles-m-blow/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/jamelle-bouie/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/david-brooks/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/frank-bruni/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/gail-collins/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ross-douthat/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/maureen-dowd/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/thomas-l-friedman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/michelle-goldberg/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ezra-klein/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/nicholas-kristof/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/paul-krugman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/farhad-manjoo/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/bret-stephens/rss.xml",    
    "https://rss.nytimes.com/services/xml/rss/nyt/sunday-review.xml",
    "https://www.washingtonpost.com/arcio/rss/category/politics/?itid=lk_inline_manual_2",
    "https://www.washingtonpost.com/arcio/rss/category/opinions/?itid=lk_inline_manual_7",
    "http://feeds.washingtonpost.com/rss/sports?itid=lk_inline_manual_20",
    "http://feeds.washingtonpost.com/rss/business/technology?itid=lk_inline_manual_31",
    "http://feeds.washingtonpost.com/rss/national?itid=lk_inline_manual_32",
    "http://feeds.washingtonpost.com/rss/world?itid=lk_inline_manual_36",
    "http://feeds.washingtonpost.com/rss/business?itid=lk_inline_manual_37",
    "http://feeds.washingtonpost.com/rss/lifestyle?itid=lk_inline_manual_38",
    "http://feeds.washingtonpost.com/rss/entertainment?itid=lk_inline_manual_39",
    "https://feeds.a.dj.com/rss/RSSOpinion.xml",
    "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    "https://feeds.a.dj.com/rss/RSSWSJD.xml",
    "https://feeds.a.dj.com/rss/RSSLifestyle.xml",
    "https://www.youtube.com/feeds/videos.xml?channel_id=UC6ZFN9Tx6xh-skXCuRHCDpQ", //PBS News Hour
    "https://theconversation.com/us/arts/articles.atom",
    "https://theconversation.com/us/business/articles.atom",
    "https://theconversation.com/us/education/articles.atom",
    "https://theconversation.com/us/environment/articles.atom",
    "https://theconversation.com/us/ethics/articles.atom",
    "https://theconversation.com/us/health/articles.atom",
    "https://theconversation.com/us/politics/articles.atom",
    "https://theconversation.com/us/technology/articles.atom",
    "https://patch.com/feeds/aol/massachusetts/boston",
    "https://feeds.npr.org/1003/rss.xml", //national
    "https://feeds.npr.org/1004/rss.xml", //world
    "https://feeds.npr.org/1006/rss.xml", //business
    "https://feeds.npr.org/1007/rss.xml", //science
    "https://feeds.npr.org/1014/rss.xml", //politics
    "https://feeds.npr.org/1015/rss.xml", //race
    "https://feeds.npr.org/1032/rss.xml", //books
    "https://feeds.npr.org/1045/rss.xml", //movies
    "https://feeds.npr.org/1048/rss.xml", //pop culture
    "https://feeds.npr.org/1128/rss.xml", //health
    "https://feeds.npr.org/1138/rss.xml", //television
    "https://feeds.npr.org/1167/rss.xml", //climate
    "https://feeds.npr.org/1001/rss.xml", //news
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCx_SjDi4CS5ALkWCS9ffldQ", //GBH News
    "https://www.wgbh.org/news/local.rss",
    "https://www.wgbh.org/news/politics.rss",
    "https://www.wgbh.org/news/education-news.rss",
    "https://www.wgbh.org/news/housing.rss",
    "https://www.wgbh.org/news/health.rss",
    "https://www.wgbh.org/news/commentary.rss",
    "https://theconversation.com/us/articles.atom",
    "https://masslawyersweekly.com/feed/", 
    "https://www.lawnext.com/feed",
    "https://www.ailawlibrarians.com/feed/",
    "https://www.scotusblog.com/feed/",
    "https://buttondown.email/LawyerExMachina/rss",
    "https://abovethelaw.com/feed/"
]

suffolk_law_feeds = suffolk_law_feeds.concat(law_school_feeds)
    
var feeds_long_list = [
    // New York Times
    "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Space.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/charles-m-blow/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/jamelle-bouie/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/david-brooks/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/frank-bruni/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/gail-collins/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/ross-douthat/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/maureen-dowd/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/thomas-l-friedman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/michelle-goldberg/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/ezra-klein/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/nicholas-kristof/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/paul-krugman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/farhad-manjoo/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/bret-stephens/rss.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/sunday-review.xml",
    // Vanity Fair
    "https://www.vanityfair.com/feed/rss",
    // NPR
    "https://feeds.npr.org/1003/rss.xml", //national
    "https://feeds.npr.org/1004/rss.xml", //world
    "https://feeds.npr.org/1006/rss.xml", //business
    "https://feeds.npr.org/1007/rss.xml", //science
    "https://feeds.npr.org/1014/rss.xml", //politics
    "https://feeds.npr.org/1015/rss.xml", //race
    "https://feeds.npr.org/1032/rss.xml", //books
    "https://feeds.npr.org/1045/rss.xml", //movies
    "https://feeds.npr.org/1048/rss.xml", //pop culture
    "https://feeds.npr.org/1128/rss.xml", //health
    "https://feeds.npr.org/1138/rss.xml", //television
    "https://feeds.npr.org/1167/rss.xml", //climate
    "https://feeds.npr.org/1001/rss.xml", //news
    // BBC
    "http://feeds.bbci.co.uk/news/world/rss.xml",
    "http://feeds.bbci.co.uk/news/uk/rss.xml",
    "http://feeds.bbci.co.uk/news/business/rss.xml",
    "http://feeds.bbci.co.uk/news/politics/rss.xml",
    "http://feeds.bbci.co.uk/news/health/rss.xml",
    "http://feeds.bbci.co.uk/news/education/rss.xml",
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    // The Guardian
    "https://www.theguardian.com/us-news/rss",
    "https://www.theguardian.com/world/rss",
    "https://www.theguardian.com/us/environment/rss",
    "https://www.theguardian.com/us/soccer/rss",
    "https://www.theguardian.com/us/business/rss",
    "https://www.theguardian.com/us/technology/rss",
    "https://www.theguardian.com/science/rss",
    "https://www.theguardian.com/us-news/series/the-fight-for-democracy/rss",
    // Washington Post
    "https://www.washingtonpost.com/arcio/rss/category/politics/?itid=lk_inline_manual_2",
    "https://www.washingtonpost.com/arcio/rss/category/opinions/?itid=lk_inline_manual_7",
    "http://feeds.washingtonpost.com/rss/sports?itid=lk_inline_manual_20",
    "http://feeds.washingtonpost.com/rss/business/technology?itid=lk_inline_manual_31",
    "http://feeds.washingtonpost.com/rss/national?itid=lk_inline_manual_32",
    "http://feeds.washingtonpost.com/rss/world?itid=lk_inline_manual_36",
    "http://feeds.washingtonpost.com/rss/business?itid=lk_inline_manual_37",
    "http://feeds.washingtonpost.com/rss/lifestyle?itid=lk_inline_manual_38",
    "http://feeds.washingtonpost.com/rss/entertainment?itid=lk_inline_manual_39",
    // The Economist
    "https://www.economist.com/the-world-this-week/rss.xml",
    "https://www.economist.com/letters/rss.xml",
    "https://www.economist.com/leaders/rss.xml",
    "https://www.economist.com/briefing/rss.xml",
    "https://www.economist.com/special-report/rss.xml",
    "https://www.economist.com/britain/rss.xml",
    "https://www.economist.com/europe/rss.xml",
    "https://www.economist.com/united-states/rss.xml",
    "https://www.economist.com/the-americas/rss.xml",
    "https://www.economist.com/middle-east-and-africa/rss.xml",
    "https://www.economist.com/asia/rss.xml",
    "https://www.economist.com/china/rss.xml",
    "https://www.economist.com/international/rss.xml",
    "https://www.economist.com/business/rss.xml",
    "https://www.economist.com/finance-and-economics/rss.xml",
    "https://www.economist.com/books-and-arts/rss.xml",
    "https://www.economist.com/obituary/rss.xml",
    "https://www.economist.com/graphic-detail/rss.xml",
    "https://www.economist.com/economic-and-financial-indicators/rss.xml",
    "https://www.economist.com/science-and-technology/rss.xml",
    // Wall Street Journal
    "https://feeds.a.dj.com/rss/RSSOpinion.xml",
    "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    "https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    "https://feeds.a.dj.com/rss/RSSWSJD.xml", // Tech What's New
    "https://feeds.a.dj.com/rss/RSSLifestyle.xml",
    // LA Times
    "https://www.latimes.com/business/rss2.0.xml",
    "https://www.latimes.com/environment/rss2.0.xml",
    "https://www.latimes.com/entertainment-arts/rss2.0.xml",
    "https://www.latimes.com/food/rss2.0.xml",
    "https://www.latimes.com/lifestyle/rss2.0.xml",
    "https://www.latimes.com/obituaries/rss2.0.xml",
    "https://www.latimes.com/opinion/rss2.0.xml",
    "https://www.latimes.com/politics/rss2.0.xml",
    "https://www.latimes.com/science/rss2.0.xml",
    "https://www.latimes.com/sports/rss2.0.xml",
    "https://www.latimes.com/travel/rss2.0.xml",
    "https://www.latimes.com/world-nation/rss2.0.xml",
    // PBS News Hour
    "https://www.youtube.com/feeds/videos.xml?channel_id=UC6ZFN9Tx6xh-skXCuRHCDpQ", 
    // Bloomberg
    "https://feeds.bloomberg.com/markets/news.rss",
    "https://feeds.bloomberg.com/politics/news.rss",
    "https://feeds.bloomberg.com/technology/news.rss",
    "https://feeds.bloomberg.com/wealth/news.rss",
    // New Yorker
    "http://www.newyorker.com/feed/news",
    "http://www.newyorker.com/feed/culture",
    "http://www.newyorker.com/feed/humor",
    "http://www.newyorker.com/feed/tag/books/rss",
    "http://www.newyorker.com/feed/tech",
    "http://www.newyorker.com/feed/news/sporting-scene",
    "https://www.theatlantic.com/feed/all/",
    "https://slate.com/feeds/news-and-politics.rss",
    // Slate
    "https://slate.com/feeds/technology.rss",
    "https://slate.com/feeds/business.rss",
    "https://slate.com/feeds/culture.rss",
    "https://slate.com/feeds/human-interest.rss",
    // The Conversation
    "https://theconversation.com/us/arts/articles.atom",
    "https://theconversation.com/us/business/articles.atom",
    "https://theconversation.com/us/education/articles.atom",
    "https://theconversation.com/us/environment/articles.atom",
    "https://theconversation.com/us/ethics/articles.atom",
    "https://theconversation.com/us/health/articles.atom",
    "https://theconversation.com/us/politics/articles.atom",
    "https://theconversation.com/us/technology/articles.atom",
    "https://theconversation.com/us/articles.atom",
    // Phys.org
    "https://phys.org/rss-feed/earth-news/",
    "https://phys.org/rss-feed/science-news/",
    "https://phys.org/rss-feed/nanotech-news/",
    "https://phys.org/rss-feed/physics-news/",
    "https://phys.org/rss-feed/space-news/",
    "https://phys.org/rss-feed/biology-news/",
    "https://phys.org/rss-feed/chemistry-news/",
    // The Gradient
    "https://thegradient.pub/rss/",
    //GBH News
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCx_SjDi4CS5ALkWCS9ffldQ", 
    "https://www.wgbh.org/news/local.rss",
    "https://www.wgbh.org/news/politics.rss",
    "https://www.wgbh.org/news/education-news.rss",
    "https://www.wgbh.org/news/housing.rss",
    "https://www.wgbh.org/news/health.rss",
    "https://www.wgbh.org/news/commentary.rss",
    // Patch
    "https://patch.com/feeds/aol/massachusetts/boston",
    "https://patch.com/feeds/aol/massachusetts/somerville",
    "https://patch.com/feeds/aol/massachusetts/cambridge",
    "https://patch.com/feeds/aol/massachusetts/arlington",
    "https://patch.com/feeds/aol/massachusetts/lexington",
    // Arstechnica
    "https://feeds.arstechnica.com/arstechnica/technology-lab",
    "https://feeds.arstechnica.com/arstechnica/tech-policy",
    "https://feeds.arstechnica.com/arstechnica/science",
    "https://feeds.arstechnica.com/arstechnica/features",
    // MIT Tech Reviw
    "https://www.technologyreview.com/feed/",
    // Wired
    "https://www.wired.com/feed/category/business/latest/rss",
    "https://www.wired.com/feed/tag/ai/latest/rss",
    "https://www.wired.com/feed/category/culture/latest/rss",
    "https://www.wired.com/feed/category/gear/latest/rss",
    "https://www.wired.com/feed/category/ideas/latest/rss",
    "https://www.wired.com/feed/category/science/latest/rss",
    "https://www.wired.com/feed/category/security/latest/rss",
    "https://www.wired.com/feed/category/backchannel/latest/rss",
    "https://www.wired.com/feed/tag/wired-guide/latest/rss",
    // Rollingstone
    "https://www.rollingstone.com/music/feed/",
    "https://www.rollingstone.com/politics/feed/",
    "https://www.rollingstone.com/tv-movies/feed/",
    "https://www.rollingstone.com/culture/feed/",
    "https://www.rollingstone.com/product-recommendations/feed/",
    // Vox
    "https://www.vox.com/rss/index.xml",
    // The Markup
    "https://themarkup.org/feeds/rss.xml",
    // ProPublica
    "https://www.propublica.org/feeds/propublica/main",
    // Lifehacker
    "http://lifehacker.com/vip.xml",
    // Them Marginalian
    "https://feeds.feedburner.com/brainpickings/rss",
    // Smithsonian Mag
    "https://www.smithsonianmag.com/rss/latest_articles/",
    // Gizmodo
    "http://gizmodo.com/vip.xml",
    // Techcrunch
    "https://techcrunch.com/feed/",
    // Pluralistic
    "https://pluralistic.net/feed/",
    // Techdirt
    "https://www.techdirt.com/techdirt_rss.xml",
    // The Information
    "https://www.theinformation.com/feed",
    // MA Lawyers Weekly
    "https://masslawyersweekly.com/feed/",
    // Law Next
    "https://www.lawnext.com/feed",
    // AI Law Librarians
    "https://www.ailawlibrarians.com/feed/",
    // SCOTUS Blog
    "https://www.scotusblog.com/feed/",
    // ExMachina Newsletter
    "https://buttondown.email/LawyerExMachina/rss",
    // SSRN
    //"https://api.ssrn.com/content/v1/journals/956475/papers/rss",
    // Above the Law
    "https://abovethelaw.com/feed/",
    // Quanta Magazine
    "https://api.quantamagazine.org/feed/",
    // Nautilus
    "https://nautil.us/feed/",
    // Aeon
    "https://aeon.co/philosophy.rss",
    "https://aeon.co/science.rss",
    "https://aeon.co/psychology.rss",
    "https://aeon.co/society.rss",
    "https://aeon.co/culture.rss",
    // Hacker News
    "https://hnrss.org/best",
    // Screen Rant
    "https://screenrant.com/feed/tag/star-trek/",
    // XKCD
    "https://xkcd.com/rss.xml",
    // McSweeney's 
    "https://feeds.feedburner.com/mcsweeneys",
    // Space News
    "https://spacenews.com/feed/",
    // Bad Astornomy 
    "https://badastronomy.substack.com/feed/",
    // 3blue1brown
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw", 
    // Cleo Abram
    "https://www.youtube.com/feeds/videos.xml?channel_id=UC415bOPUcGSamy543abLmRA", 
    // Veritasium 
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA", 
    // Astronomy Picture of the Day
    "https://botsin.space/@APoD.rss",
    // Clarksworld
    "https://clarkesworldmagazine.com/feed/",
    // Lightspeed
    "https://www.lightspeedmagazine.com/rss-2/",
    // Escape Pod
    "https://escapepod.org/feed/podcast/",
    // Tor
    "https://tor.com/feed"
]

test_feeds = [

    // New York Times
    "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/US.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    //"https://rss.nytimes.com/services/xml/rss/nyt/Sports.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Space.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Health.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/charles-m-blow/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/jamelle-bouie/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/david-brooks/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/frank-bruni/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/gail-collins/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/ross-douthat/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/maureen-dowd/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/thomas-l-friedman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/michelle-goldberg/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/ezra-klein/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/nicholas-kristof/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/paul-krugman/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/farhad-manjoo/rss.xml",
    "https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/by/bret-stephens/rss.xml",
    "https://rss.nytimes.com/services/xml/rss/nyt/sunday-review.xml",
    // Vanity Fair
    "https://www.vanityfair.com/feed/rss",
    // NPR
    "https://feeds.npr.org/1003/rss.xml", //national
    "https://feeds.npr.org/1004/rss.xml", //world
    "https://feeds.npr.org/1006/rss.xml", //business
    "https://feeds.npr.org/1007/rss.xml", //science
    "https://feeds.npr.org/1014/rss.xml", //politics
    "https://feeds.npr.org/1015/rss.xml", //race
    "https://feeds.npr.org/1032/rss.xml", //books
    "https://feeds.npr.org/1045/rss.xml", //movies
    "https://feeds.npr.org/1048/rss.xml", //pop culture
    "https://feeds.npr.org/1128/rss.xml", //health
    "https://feeds.npr.org/1138/rss.xml", //television
    "https://feeds.npr.org/1167/rss.xml", //climate
    "https://feeds.npr.org/1001/rss.xml", //news
    // BBC
    "http://feeds.bbci.co.uk/news/world/rss.xml",
    //"http://feeds.bbci.co.uk/news/uk/rss.xml",
    "http://feeds.bbci.co.uk/news/business/rss.xml",
    //"http://feeds.bbci.co.uk/news/politics/rss.xml",
    "http://feeds.bbci.co.uk/news/health/rss.xml",
    "http://feeds.bbci.co.uk/news/education/rss.xml",
    "http://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
    "http://feeds.bbci.co.uk/news/technology/rss.xml",
    "http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    // The Guardian
    "https://www.theguardian.com/us-news/rss",
    "https://www.theguardian.com/world/rss",
    "https://www.theguardian.com/us/environment/rss",
    //"https://www.theguardian.com/us/soccer/rss",
    "https://www.theguardian.com/us/business/rss",
    "https://www.theguardian.com/us/technology/rss",
    "https://www.theguardian.com/science/rss",
    "https://www.theguardian.com/us-news/series/the-fight-for-democracy/rss",
    // Washington Post
    "https://www.washingtonpost.com/arcio/rss/category/politics/?itid=lk_inline_manual_2",
    "https://www.washingtonpost.com/arcio/rss/category/opinions/?itid=lk_inline_manual_7",
    //"http://feeds.washingtonpost.com/rss/sports?itid=lk_inline_manual_20",
    "http://feeds.washingtonpost.com/rss/business/technology?itid=lk_inline_manual_31",
    "http://feeds.washingtonpost.com/rss/national?itid=lk_inline_manual_32",
    "http://feeds.washingtonpost.com/rss/world?itid=lk_inline_manual_36",
    "http://feeds.washingtonpost.com/rss/business?itid=lk_inline_manual_37",
    "http://feeds.washingtonpost.com/rss/lifestyle?itid=lk_inline_manual_38",
    "http://feeds.washingtonpost.com/rss/entertainment?itid=lk_inline_manual_39",
    // The Economist
    "https://www.economist.com/the-world-this-week/rss.xml",
    "https://www.economist.com/letters/rss.xml",
    "https://www.economist.com/leaders/rss.xml",
    "https://www.economist.com/briefing/rss.xml",
    "https://www.economist.com/special-report/rss.xml",
    "https://www.economist.com/britain/rss.xml",
    "https://www.economist.com/europe/rss.xml",
    "https://www.economist.com/united-states/rss.xml",
    "https://www.economist.com/the-americas/rss.xml",
    "https://www.economist.com/middle-east-and-africa/rss.xml",
    "https://www.economist.com/asia/rss.xml",
    "https://www.economist.com/china/rss.xml",
    "https://www.economist.com/international/rss.xml",
    "https://www.economist.com/business/rss.xml",
    "https://www.economist.com/finance-and-economics/rss.xml",
    "https://www.economist.com/books-and-arts/rss.xml",
    "https://www.economist.com/obituary/rss.xml",
    "https://www.economist.com/graphic-detail/rss.xml",
    "https://www.economist.com/economic-and-financial-indicators/rss.xml",
    "https://www.economist.com/science-and-technology/rss.xml",
    // Wall Street Journal
    //"https://feeds.a.dj.com/rss/RSSOpinion.xml",
    "https://feeds.a.dj.com/rss/RSSWorldNews.xml",
    "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml",
    //"https://feeds.a.dj.com/rss/RSSMarketsMain.xml",
    "https://feeds.a.dj.com/rss/RSSWSJD.xml", // Tech What's New
    "https://feeds.a.dj.com/rss/RSSLifestyle.xml",
    // LA Times
    "https://www.latimes.com/business/rss2.0.xml",
    "https://www.latimes.com/environment/rss2.0.xml",
    "https://www.latimes.com/entertainment-arts/rss2.0.xml",
    //"https://www.latimes.com/food/rss2.0.xml",
    "https://www.latimes.com/lifestyle/rss2.0.xml",
    //"https://www.latimes.com/obituaries/rss2.0.xml",
    "https://www.latimes.com/opinion/rss2.0.xml",
    "https://www.latimes.com/politics/rss2.0.xml",
    "https://www.latimes.com/science/rss2.0.xml",
    //"https://www.latimes.com/sports/rss2.0.xml",
    "https://www.latimes.com/travel/rss2.0.xml",
    "https://www.latimes.com/world-nation/rss2.0.xml",
    // PBS News Hour
    "https://www.youtube.com/feeds/videos.xml?channel_id=UC6ZFN9Tx6xh-skXCuRHCDpQ", 
    // Bloomberg
    //"https://feeds.bloomberg.com/markets/news.rss",
    //"https://feeds.bloomberg.com/politics/news.rss",
    //"https://feeds.bloomberg.com/technology/news.rss",
    //"https://feeds.bloomberg.com/wealth/news.rss",
    // New Yorker
    "http://www.newyorker.com/feed/news",
    "http://www.newyorker.com/feed/culture",
    "http://www.newyorker.com/feed/humor",
    "http://www.newyorker.com/feed/tag/books/rss",
    "http://www.newyorker.com/feed/tech",
    //"http://www.newyorker.com/feed/news/sporting-scene",
    "https://www.theatlantic.com/feed/all/",
    "https://slate.com/feeds/news-and-politics.rss",
    // Slate
    "https://slate.com/feeds/technology.rss",
    "https://slate.com/feeds/business.rss",
    "https://slate.com/feeds/culture.rss",
    "https://slate.com/feeds/human-interest.rss",
    // The Conversation
    "https://theconversation.com/us/arts/articles.atom",
    "https://theconversation.com/us/business/articles.atom",
    "https://theconversation.com/us/education/articles.atom",
    "https://theconversation.com/us/environment/articles.atom",
    "https://theconversation.com/us/ethics/articles.atom",
    "https://theconversation.com/us/health/articles.atom",
    "https://theconversation.com/us/politics/articles.atom",
    "https://theconversation.com/us/technology/articles.atom",
    "https://theconversation.com/us/articles.atom",
    // Phys.org
    //"https://phys.org/rss-feed/earth-news/",
    "https://phys.org/rss-feed/science-news/",
    //"https://phys.org/rss-feed/nanotech-news/",
    "https://phys.org/rss-feed/physics-news/",
    "https://phys.org/rss-feed/space-news/",
    //"https://phys.org/rss-feed/biology-news/",
    //"https://phys.org/rss-feed/chemistry-news/",
    // The Gradient
    "https://thegradient.pub/rss/",
    //GBH News
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCx_SjDi4CS5ALkWCS9ffldQ", 
    "https://www.wgbh.org/news/local.rss",
    "https://www.wgbh.org/news/politics.rss",
    "https://www.wgbh.org/news/education-news.rss",
    "https://www.wgbh.org/news/housing.rss",
    "https://www.wgbh.org/news/health.rss",
    "https://www.wgbh.org/news/commentary.rss",
    // Patch
    "https://patch.com/feeds/aol/massachusetts/boston",
    "https://patch.com/feeds/aol/massachusetts/somerville",
    "https://patch.com/feeds/aol/massachusetts/cambridge",
    "https://patch.com/feeds/aol/massachusetts/arlington",
    "https://patch.com/feeds/aol/massachusetts/lexington",
    // Arstechnica
    "https://feeds.arstechnica.com/arstechnica/technology-lab",
    "https://feeds.arstechnica.com/arstechnica/tech-policy",
    "https://feeds.arstechnica.com/arstechnica/science",
    "https://feeds.arstechnica.com/arstechnica/features",
    // MIT Tech Reviw
    "https://www.technologyreview.com/feed/",
    // Wired
    "https://www.wired.com/feed/category/business/latest/rss",
    "https://www.wired.com/feed/tag/ai/latest/rss",
    "https://www.wired.com/feed/category/culture/latest/rss",
    //"https://www.wired.com/feed/category/gear/latest/rss",
    "https://www.wired.com/feed/category/ideas/latest/rss",
    "https://www.wired.com/feed/category/science/latest/rss",
    "https://www.wired.com/feed/category/security/latest/rss",
    "https://www.wired.com/feed/category/backchannel/latest/rss",
    "https://www.wired.com/feed/tag/wired-guide/latest/rss",
    // Rollingstone
    "https://www.rollingstone.com/music/feed/",
    "https://www.rollingstone.com/politics/feed/",
    "https://www.rollingstone.com/tv-movies/feed/",
    "https://www.rollingstone.com/culture/feed/",
    //"https://www.rollingstone.com/product-recommendations/feed/",
    // Vox
    "https://www.vox.com/rss/index.xml",
    // The Markup
    "https://themarkup.org/feeds/rss.xml",
    // ProPublica
    "https://www.propublica.org/feeds/propublica/main",
    // Lifehacker
    "http://lifehacker.com/vip.xml",
    // Them Marginalian
    "https://feeds.feedburner.com/brainpickings/rss",
    // Smithsonian Mag
    "https://www.smithsonianmag.com/rss/latest_articles/",
    // Gizmodo
    //"http://gizmodo.com/vip.xml",
    // Techcrunch
    "https://techcrunch.com/feed/",
    // Pluralistic
    "https://pluralistic.net/feed/",
    // Techdirt
    "https://www.techdirt.com/techdirt_rss.xml",
    // The Information
    //"https://www.theinformation.com/feed",
    // MA Lawyers Weekly
    "https://masslawyersweekly.com/feed/",
    // Law Next
    "https://www.lawnext.com/feed",
    // AI Law Librarians
    "https://www.ailawlibrarians.com/feed/",
    // SCOTUS Blog
    "https://www.scotusblog.com/feed/",
    // ExMachina Newsletter
    "https://buttondown.email/LawyerExMachina/rss",
    // SSRN
    "https://api.ssrn.com/content/v1/journals/956475/papers/rss",
    // Above the Law
    "https://abovethelaw.com/feed/",
    // Quanta Magazine
    "https://api.quantamagazine.org/feed/",
    //  Nautilus
    "https://nautil.us/feed/",
    // Aeon
    "https://aeon.co/philosophy.rss",
    "https://aeon.co/science.rss",
    "https://aeon.co/psychology.rss",
    "https://aeon.co/society.rss",
    "https://aeon.co/culture.rss",
    // Hacker News
    "https://hnrss.org/best",
    // Screen Rant
    "https://screenrant.com/feed/tag/star-trek/",
    // XKCD
    "https://xkcd.com/rss.xml",
    // McSweeney's 
    "https://feeds.feedburner.com/mcsweeneys",
    // Space News
    "https://spacenews.com/feed/",
    // Bad Astornomy 
    "https://badastronomy.substack.com/feed/",
    // 3blue1brown
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCYO_jab_esuFRV4b17AJtAw", 
    // Cleo Abram
    "https://www.youtube.com/feeds/videos.xml?channel_id=UC415bOPUcGSamy543abLmRA", 
    // Veritasium 
    "https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA", 
    // Astronomy Picture of the Day
    "https://botsin.space/@APoD.rss",
    // Clarksworld
    "https://clarkesworldmagazine.com/feed/",
    // Lightspeed
    "https://www.lightspeedmagazine.com/rss-2/",
    // Escape Pod
    "https://escapepod.org/feed/podcast/",
    // Tor
    "https://tor.com/feed"

    // CORS proxy doesn't resolve feed (entierly broken)
    //"http://rss.sciam.com/ScientificAmerican-Global",

    // Seems to "work" but there are no new posts
    //"https://lawprofblawg.wordpress.com/feed/",
    //"https://www.reutersagency.com/feed/?best-regions=north-america&post_type=best",

]

//default_feeds = test_feeds
